# Generated by Django 2.1.2 on 2018-11-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181105_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unidad'), ('gram', 'Gramo'), ('pound', 'Libra'), ('kilogram', 'Kilogramo')], default='unit', max_length=20, verbose_name='Unidad de venta'),
        ),
        migrations.AlterField(
            model_name='siteproduct',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='siteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='siteproduct',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitio de Venta'),
        ),
    ]
