# Generated by Django 2.1.2 on 2018-11-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181105_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteproduct',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Precio por Unidad de venta'),
        ),
    ]
