# Generated by Django 2.1.2 on 2018-11-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20181117_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteproduct',
            name='newPrice',
            field=models.FloatField(default=0.0, verbose_name='Precio nuevo al modificar'),
        ),
        migrations.AlterField(
            model_name='siteproduct',
            name='status',
            field=models.CharField(choices=[('Sin cambios', 'Sin cambios'), ('Nuevo', 'Nuevo'), ('Modificado', 'Modificado')], default='Sin cambios', max_length=20, verbose_name='Estado de almacenamiento'),
        ),
    ]
