# Generated by Django 2.1.2 on 2018-11-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20181105_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=750, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='sites', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='site',
            name='timeOpen',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Horario'),
        ),
        migrations.AlterField(
            model_name='site',
            name='webSite',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Sitio Web'),
        ),
    ]
